### ISSUE TITLE
Context not set.

### ISSUE THREAD

**Issue by Byteron** [Doraku/Ecs.CSharp.Benchmark#1]
Hello. I am trying to integrate my own ECS in this benchmark.
I have everything set up, basically "copied" from other ECSes and replaced it with my stuff.

However when I now run the benchmark I get a null reference exception.
It seems that the `private <EcsName>Context _context;` is not automatically set, as it is null.
But it is null only for my ECS benches. In the others it is also not initialized and it works there.

**Comment by Byteron** [comment]
```csharp
namespace Ecs.CSharp.Benchmark
{
    public partial class CreateEntityWithOneComponent
    {
        private BitronEcsBaseContext _bitronEcs;

        [BenchmarkCategory(Categories.BitronEcs)]
        [Benchmark]
        public void BitronEcs()
        {
            for (int i = 0; i < EntityCount; ++i)
            {
                _bitronEcs.World.Spawn().Add<BitronEcsBaseContext.Component1>();
            }
        }
    }
}
```
_bitronEcs is null, it says.
```csharp
namespace Ecs.CSharp.Benchmark
{
    public partial class CreateEntityWithOneComponent
    {
        private LeopotamEcsLiteBaseContext _leopotamEcsLite;

        [BenchmarkCategory(Categories.LeopotamEcsLite)]
        [Benchmark]
        public void LeopotamEcsLite()
        {
            EcsPool<LeopotamEcsLiteBaseContext.Component1> c1 = _leopotamEcsLite.World.GetPool<LeopotamEcsLiteBaseContext.Component1>();

            for (int i = 0; i < EntityCount; ++i)
            {
                c1.Add(_leopotamEcsLite.World.NewEntity());
            }
        }
    }
}
```
it's the same in other benchmarks and there it does not crash.

**Comment by Byteron** [comment]
Ah, I see.
DefaultEcs is *not* another EcsLibrary. I have to actually create mine in these too.

**Comment by Doraku** [comment]
Yes sorry I cut some corner here ^^" The tests need to be in the same type to be compared with a baseline, and I didn't want to have a big file with every framework implementation in there (especially so since we have conflicting type names) so I split everything and put the initialisation logic in the DefaultEcs partial definitions (`Setup` and `Cleanup`), XUnit does not allow multiple methods with those attributes sadly :( There is probably a smarter way to do it without being this confusing for people wanting to add their own implementation.
